name: Load .env from GitHub Secrets

on:
  push:
    branches: [main]

jobs:
  setup-env:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate .env from Secrets
        run: |
          echo "REPO_GITHUB=${{ secrets.REPO_GITHUB }}" >> .env
          echo "TOKEN_GITHUB=${{ secrets.TOKEN_GITHUB }}" >> .env
          echo "DISCORD_TOKEN=${{ secrets.DISCORD_TOKEN }}" >> .env
          echo "DISCORD_CLIENT_ID=${{ secrets.DISCORD_CLIENT_ID }}" >> .env
          echo "DISCORD_CLIENT_SECRET=${{ secrets.DISCORD_CLIENT_SECRET }}" >> .env
          echo "DISCORD_GUILD_ID=${{ secrets.DISCORD_GUILD_ID }}" >> .env
          echo "DISCORD_CHANNEL_ID=${{ secrets.DISCORD_CHANNEL_ID }}" >> .env
          echo "DISCORD_ADMIN_ROLE_ID=${{ secrets.DISCORD_ADMIN_ROLE_ID }}" >> .env
          echo "ADMIN_ROLE_IDS=${{ secrets.ADMIN_ROLE_IDS }}" >> .env
          echo "R4_ROLE_IDS=${{ secrets.R4_ROLE_IDS }}" >> .env
          echo "R3_ROLE_IDS=${{ secrets.R3_ROLE_IDS }}" >> .env
          echo "BASE_URL=${{ secrets.BASE_URL }}" >> .env
          echo "DISCORD_WEBHOOK_URL=${{ secrets.DISCORD_WEBHOOK_URL }}" >> .env
          echo "DISCORD_REDIRECT_URI=${{ secrets.DISCORD_REDIRECT_URI }}" >> .env

          echo "SESSION_SECRET=${{ secrets.SESSION_SECRET }}" >> .env
          echo "OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}" >> .env
          echo "DATABASE_PATH=${{ secrets.DATABASE_PATH }}" >> .env
          echo "FLASK_ENV=${{ secrets.FLASK_ENV }}" >> .env

          echo "GOOGLE_CLIENT_ID=${{ secrets.GOOGLE_CLIENT_ID }}" >> .env
          echo "GOOGLE_PROJECT_ID=${{ secrets.GOOGLE_PROJECT_ID }}" >> .env
          echo "GOOGLE_CLIENT_SECRET=${{ secrets.GOOGLE_CLIENT_SECRET }}" >> .env
          echo "GOOGLE_AUTH_URI=${{ secrets.GOOGLE_AUTH_URI }}" >> .env
          echo "GOOGLE_TOKEN_URI=${{ secrets.GOOGLE_TOKEN_URI }}" >> .env
          echo "GOOGLE_AUTH_PROVIDER_CERT_URL=${{ secrets.GOOGLE_AUTH_PROVIDER_CERT_URL }}" >> .env
          echo "GOOGLE_REDIRECT_URI=${{ secrets.GOOGLE_REDIRECT_URI }}" >> .env
